---
- name: Aplicar actualizaciones
  hosts: all
  become: true

  tasks:

  - name: Instalar todas las actualizaciones de seguridad de Red Hat
    ansible.builtin.dnf:
      name: "*"
      state: latest
    when: ansible_os_family == "RedHat"
    notify: Reiniciar

  - name: Instalar todas las actualizaciones de Debian
    ansible.builtin.apt:
      name: "*"
      update_cache: true
      state: latest
    when: ansible_os_family == "Debian"
    notify: Reiniciar


  handlers:

  - name: Reiniciar
    ansible.builtin.reboot:
      msg: "Reiniciando por actualizaciones"
